# Run hastygram with
#    $ uvicorn hastygram.app:app
# or $ python hastygram/app.py --port 8000
#
# Build the frontend with
#    $ cd web ; yarn run build
#
# nginx listens on 8080.

version: "3"

services:
  nginx:
    image: nginx:mainline-alpine
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web/build:/build:ro
