version: "3"

services:
  # nginx listens on 8080, hastygram API on its default 8000.
  nginx:
    image: nginx:mainline-alpine
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web/build:/build:ro
